# build-package.yml
name: Package on Release Draft

on:
  release:
    types: [created, edited]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' 

      - name: Extract version and package
        run: |
          echo "Fetching release information..."
          RELEASE_INFO=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.event.release.tag_name }})
          VERSION=$(echo "$RELEASE_INFO" | jq -r '.tag_name')
          echo "Extracted version: $VERSION"
          
          echo "Packing with version: $VERSION"
          dotnet pack src/Messaging/Messaging.csproj -p:PackageVersion=$VERSION --no-build -o nupkgs
