# .github/workflows/CI-Build-and-Package.yml

name: CI Build, Test, and Package

on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore src/Messaging/Messaging.csproj

      - name: Build
        run: dotnet build src/Messaging/Messaging.csproj --no-restore

      - name: Test
        run: dotnet test src/Messaging/Messaging.csproj --no-build

  package:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Package NuGet
        run: dotnet pack src/Messaging/Messaging.csproj --no-build -o nupkgs
