name: .NET CI/CD

# Versionierungsstrategie:
# Für den main-Branch werden Releases mit der in der .csproj-Datei festgelegten Version erstellt,
# die manuell vor dem Merge angepasst werden sollte. Dies ermöglicht eine präzise Kontrolle über Major und Minor Releases.
# Für alle anderen Branches werden automatische Zwischenreleases mit einem Datumssuffix generiert, um kontinuierliches Testing und Feedback
# für Entwicklungsstände zu ermöglichen. Das Datumssuffix wird basierend auf dem aktuellen Datum und der Uhrzeit zum Zeitpunkt des Builds hinzugefügt,
# was jede Version einzigartig macht.

on:
  push:
    branches:
      - '**'

jobs:
  build_and_pack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore src/Messaging/Messaging.csproj

      # Schritt: Lese die PackageVersion aus der .csproj Datei
      # Dieser Schritt nutzt grep und sed, um den Wert des PackageVersion-Elements aus der .csproj-Datei zu extrahieren.
      # Der extrahierte Wert wird dann als Output dieses Schrittes gesetzt, damit er in nachfolgenden Schritten verwendet werden kann.
      - name: Read Package Version from .csproj
        id: read_version
        run: |
          csprojFile='src/Messaging/Messaging.csproj' # Der Pfad zur .csproj-Datei
          version=$(grep '<PackageVersion>' "$csprojFile" | sed -n -e 's/.*<PackageVersion>\(.*\)<\/PackageVersion>.*/\1/p')
          echo "Basisversion ist $version"
          echo "::set-output name=base_version::$version"

      # Schritt: Build und Pack
      # Basierend auf dem Branch, der den Workflow ausgelöst hat, entscheidet dieser Schritt,
      # ob ein normales Release (main-Branch) oder ein Zwischenrelease (andere Branches) durchgeführt wird.
      # Für ein Zwischenrelease wird der ausgelesenen Basisversion ein Datumssuffix hinzugefügt.
      - name: Build and Pack
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            # Wenn der Commit im main-Branch ist, packen wir ohne Änderung der Version,
            # die Version wird direkt aus der .csproj-Datei gelesen.
            dotnet pack --configuration Release --output nupkgs
          else
            # Für Commits in anderen Branches fügen wir der Basisversion ein Datumssuffix hinzu,
            # um eine einzigartige Zwischenversion zu erzeugen.
            dateSuffix=$(date +"%Y%m%d%H%M")
            version="${{ steps.read_version.outputs.base_version }}-$dateSuffix"
            dotnet pack /p:PackageVersion=$version --configuration Release --output nupkgs
            echo "Zwischenversion ist $version"
          fi

      - name: Push NuGet Package
        run: dotnet nuget push "nupkgs/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
