name: CI, Release Drafting, and Packaging

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CURRENT_VERSION: '' # Dieser Wert wird von GitHub aus dem letzten veröffentlichen Release ermittelt
  CURRENT_RELEASE_NOTES: '' # Dieser Wert wird von GitHub aus dem letzten veröffentlichen Release ermittelt
  NEXT_MINOR_VERSION: '' # Dieser Wert wird in den Jobs berechnet

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Install dependencies
        run: dotnet restore src/Messaging/Messaging.csproj
      - name: Build
        run: dotnet build src/Messaging/Messaging.csproj --no-restore
      - name: Test
        run: dotnet test src/Messaging/Messaging.csproj --no-build
  
  release_draft_and_pack: