# .github/workflows/release-drafter.yml im zentralen Repository
name: 'Release Drafter'

on:
  workflow_call:
    secrets:
      custom_github_token:  # Verändert von github_token zu custom_github_token
        required: true

jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          config-name: 'release-drafter-config.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.custom_github_token }}  # Verwendet jetzt custom_github_token
